<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>Smile.VisualStudio</RootNamespace>
    <AssemblyName>Smile.VisualStudio</AssemblyName>
    <Version>2.0.30</Version>
    <AssemblyVersion>2.0.30.0</AssemblyVersion>
    <FileVersion>2.0.30.0</FileVersion>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <IncludeAssemblyInVSIXContainer>true</IncludeAssemblyInVSIXContainer>
    <IncludeDebugSymbolsInVSIXContainer>false</IncludeDebugSymbolsInVSIXContainer>
    <CopyBuildOutputToOutputDirectory>true</CopyBuildOutputToOutputDirectory>
    <UseCodebase>true</UseCodebase>
    <DeployExtension>false</DeployExtension>
    <CreateVsixContainer>true</CreateVsixContainer>
    <VSSDKBuildToolsAutoSetup>true</VSSDKBuildToolsAutoSetup>
    <GeneratePkgDefFile>true</GeneratePkgDefFile>
    <NoWarn>$(NoWarn);VSSDK007</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.ComponentModel.Composition" />
    <Reference Include="System.Design" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
    <ProjectReference Include="..\Smile.Language\Smile.Language.csproj">
      <Private>true</Private>
      <IncludeOutputGroupsInVSIX>BuiltProjectOutputGroup</IncludeOutputGroupsInVSIX>
    </ProjectReference>
    <ProjectReference Include="Templates\Smile.ProjectTemplates.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <IncludeOutputGroupsInVSIX>TemplateProjectOutputGroup</IncludeOutputGroupsInVSIX>
      <VSIXSubPath>ProjectTemplates</VSIXSubPath>
      <GlobalPropertiesToRemove>DeployExtension;VSSDKTargetPlatformRegRootSuffix</GlobalPropertiesToRemove>
    </ProjectReference>
    <ProjectReference Include="Templates\Items\Smile.ItemTemplates.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <IncludeOutputGroupsInVSIX>TemplateProjectOutputGroup</IncludeOutputGroupsInVSIX>
      <VSIXSubPath>ItemTemplates</VSIXSubPath>
      <GlobalPropertiesToRemove>DeployExtension;VSSDKTargetPlatformRegRootSuffix</GlobalPropertiesToRemove>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.SDK" Version="17.14.40265" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.VSSDK.BuildTools" Version="18.5.40034" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <VSCTCompile Include="Commands.vsct">
      <ResourceName>Menus.ctmenu</ResourceName>
    </VSCTCompile>
    <None Include="source.extension.vsixmanifest">
      <SubType>Designer</SubType>
    </None>
    <Content Include="..\..\artifacts\compiler\**\*">
      <Link>Compiler\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
  </ItemGroup>
</Project>
