#ifndef SMILE_GRAPHICS3D_H
#define SMILE_GRAPHICS3D_H

#include <wchar.h>

#ifdef __cplusplus
extern "C" {
#endif

enum SmileRenderer3DCommand
{
    SMILE_3D_AVAILABLE = 1,
    SMILE_3D_RESET = 2,
    SMILE_3D_CREATE_MESH = 3,
    SMILE_3D_SET_VERTEX = 4,
    SMILE_3D_SET_TRIANGLE = 5,
    SMILE_3D_COMMIT_MESH = 6,
    SMILE_3D_CREATE_PRIMITIVE = 7,
    SMILE_3D_CREATE_OBJECT = 8,
    SMILE_3D_DESTROY = 9,
    SMILE_3D_SET_CAMERA = 10,
    SMILE_3D_SET_POSITION = 11,
    SMILE_3D_SET_ROTATION = 12,
    SMILE_3D_SET_SCALE = 13,
    SMILE_3D_SET_COLOR = 14,
    SMILE_3D_SET_VISIBLE = 15,
    SMILE_3D_BEGIN = 16,
    SMILE_3D_DRAW = 17,
    SMILE_3D_END = 18,
    SMILE_3D_MESH_VERTEX_COUNT = 19,
    SMILE_3D_MESH_INDEX_COUNT = 20,
    SMILE_3D_LAST_ERROR = 21,
    SMILE_3D_LIVE_MESH_COUNT = 22,
    SMILE_3D_LIVE_OBJECT_COUNT = 23,
    SMILE_3D_MAX_MESH_COUNT = 24,
    SMILE_3D_MAX_OBJECT_COUNT = 25,
    SMILE_3D_MESH_VALID = 26,
    SMILE_3D_OBJECT_VALID = 27,
    SMILE_3D_MESH_REFERENCE_COUNT = 28,
    SMILE_3D_CREATE_MATERIAL = 29,
    SMILE_3D_SET_OBJECT_MATERIAL = 30,
    SMILE_3D_SET_MESH_UV = 31,
    SMILE_3D_LIVE_TEXTURE_COUNT = 32,
    SMILE_3D_LIVE_MATERIAL_COUNT = 33,
    SMILE_3D_MAX_TEXTURE_COUNT = 34,
    SMILE_3D_MAX_MATERIAL_COUNT = 35,
    SMILE_3D_TEXTURE_VALID = 36,
    SMILE_3D_MATERIAL_VALID = 37,
    SMILE_3D_TEXTURE_WIDTH = 38,
    SMILE_3D_TEXTURE_HEIGHT = 39,
    SMILE_3D_TEXTURE_REFERENCE_COUNT = 40,
    SMILE_3D_MATERIAL_REFERENCE_COUNT = 41,
    SMILE_3D_SET_MATERIAL = 42,
    SMILE_3D_SET_MESH_NORMAL = 43,
    SMILE_3D_LIVE_MODEL_COUNT = 44,
    SMILE_3D_MAX_MODEL_COUNT = 45,
    SMILE_3D_MODEL_VALID = 46,
    SMILE_3D_MODEL_PART_COUNT = 47,
    SMILE_3D_MODEL_MATERIAL_COUNT = 48,
    SMILE_3D_CREATE_MODEL_PART_OBJECT = 49,
    SMILE_3D_MODEL_PART_MATERIAL = 50,
    SMILE_3D_SET_MESH_SKIN = 51,
    SMILE_3D_CREATE_SKELETON = 52,
    SMILE_3D_SET_SKELETON_BONE = 53,
    SMILE_3D_COMMIT_SKELETON = 54,
    SMILE_3D_CREATE_CLIP = 55,
    SMILE_3D_SET_CLIP_TRANSLATION = 56,
    SMILE_3D_SET_CLIP_ROTATION = 57,
    SMILE_3D_SET_CLIP_SCALE = 58,
    SMILE_3D_ADD_CLIP_EVENT = 59,
    SMILE_3D_CREATE_ANIMATOR = 60,
    SMILE_3D_PLAY_ANIMATOR = 61,
    SMILE_3D_UPDATE_ANIMATOR = 62,
    SMILE_3D_ANIMATOR_COMPLETE = 63,
    SMILE_3D_ANIMATOR_TIME = 64,
    SMILE_3D_TAKE_ANIMATOR_EVENT = 65,
    SMILE_3D_SET_OBJECT_ANIMATOR = 66,
    SMILE_3D_LIVE_SKELETON_COUNT = 67,
    SMILE_3D_LIVE_CLIP_COUNT = 68,
    SMILE_3D_LIVE_ANIMATOR_COUNT = 69,
    SMILE_3D_MAX_BONE_COUNT = 70,
    SMILE_3D_SKELETON_VALID = 71,
    SMILE_3D_CLIP_VALID = 72,
    SMILE_3D_ANIMATOR_VALID = 73,
    SMILE_3D_STOP_ANIMATOR = 74,
    SMILE_3D_MAX_SKELETON_COUNT = 75,
    SMILE_3D_MAX_CLIP_COUNT = 76,
    SMILE_3D_MAX_ANIMATOR_COUNT = 77,
    SMILE_3D_DRAW_CALL_COUNT = 78,
    SMILE_3D_SUBMITTED_TRIANGLE_COUNT = 79,
    SMILE_3D_MODEL_STATIC_VALUE = 80,
    SMILE_3D_CREATE_PBR_MATERIAL = 81,
    SMILE_3D_SET_PBR_FACTORS = 82,
    SMILE_3D_SET_PBR_EMISSIVE = 83,
    SMILE_3D_SET_PBR_TEXTURES = 84,
    SMILE_3D_RESET_LIGHTS = 85,
    SMILE_3D_SET_AMBIENT_LIGHT = 86,
    SMILE_3D_SET_DIRECTIONAL_LIGHT = 87,
    SMILE_3D_SET_LOCAL_LIGHT = 88,
    SMILE_3D_SET_SPOT_CONE = 89,
    SMILE_3D_PBR_TEXTURE_VALUE = 90,
    SMILE_3D_PBR_MATERIAL_VALUE = 91,
    SMILE_3D_LIGHT_VALUE = 92,
    SMILE_3D_PBR_DRAW_COUNT = 93,
    SMILE_3D_SIMPLE_DRAW_COUNT = 94,
    SMILE_3D_PBR_TRIANGLE_COUNT = 95,
    SMILE_3D_PBR_SHADER_AVAILABLE = 96,
    SMILE_3D_MODEL_PBR_VALUE = 97,
    SMILE_3D_MODEL_ANIMATION_VALUE = 98,
    SMILE_3D_CREATE_MODEL_ANIMATOR = 99,
    SMILE_3D_PLAY_MODEL_ANIMATOR = 100,
    SMILE_3D_CROSSFADE_MODEL_ANIMATOR = 101,
    SMILE_3D_ANIMATOR_CLIP_INDEX = 102,
    SMILE_3D_ANIMATOR_FADE_PERCENT = 103,
    SMILE_3D_ANIMATOR_PENDING_EVENT_COUNT = 104,
    SMILE_3D_SET_ANIMATOR_ROOT_MOTION = 105,
    SMILE_3D_TAKE_ANIMATOR_ROOT_DELTA = 106,
    SMILE_3D_ANIMATOR_SOCKET_VALUE = 107,
    SMILE_3D_MODEL_ANIMATION_AVAILABLE = 108,
    SMILE_3D_MODEL_PALETTE_UPLOAD_COUNT = 109,
    SMILE_3D_ANIMATOR_PRODUCTION_VALUE = 110,
    SMILE_3D_CLEAR_ANIMATOR_EVENTS = 111,
    SMILE_3D_RENDERER_STATE = 112,
    SMILE_3D_CONFIGURE_POST = 113,
    SMILE_3D_CONFIGURE_SHADOW = 114,
    SMILE_3D_SET_SHADOW_AREA = 115,
    SMILE_3D_SET_OBJECT_SHADOWS = 116,
    SMILE_3D_M5_VALUE = 117,
    SMILE_3D_SUBMISSION_GROUP = 118,
    SMILE_3D_PARTICLE_BATCH = 119,
    SMILE_3D_RIBBON_BATCH = 120,
    SMILE_3D_M6_VALUE = 121,
    SMILE_3D_MATERIAL_INSPECTION = 122,
    SMILE_3D_SET_CAMERA_UP = 123,
    SMILE_3D_SET_MODEL_ANIMATOR_TIME = 124,
    SMILE_3D_SOFT_DEPTH = 125
};

enum SmileRenderer3DImageCommand
{
    SMILE_3D_IMAGE_CREATE_TEXTURE = 1,
    SMILE_3D_IMAGE_CREATE_PBR_TEXTURE = 2
};

enum SmileRenderer3DTextCommand
{
    SMILE_3D_TEXT_LOAD_MODEL = 1,
    SMILE_3D_TEXT_LOAD_MODEL_GEOMETRY = 2,
    SMILE_3D_TEXT_PREPARE_MODEL_PBR = 3,
    SMILE_3D_TEXT_MODEL_CLIP_INDEX = 4,
    SMILE_3D_TEXT_MODEL_SOCKET_INDEX = 5,
    SMILE_3D_TEXT_MODEL_EVENT_NAME_MATCHES = 6,
    SMILE_3D_TEXT_PLAY_MODEL_ANIMATOR = 7,
    SMILE_3D_TEXT_CROSSFADE_MODEL_ANIMATOR = 8,
    SMILE_3D_TEXT_TAKE_MODEL_ANIMATOR_EVENT = 9,
    SMILE_3D_TEXT_MODEL_CLIP_NAME = 10,
    SMILE_3D_TEXT_MODEL_SOCKET_NAME = 11,
    SMILE_3D_TEXT_MODEL_EVENT_NAME = 12
};

enum SmilePrimitive3D
{
    SMILE_3D_CUBE = 1,
    SMILE_3D_PLANE = 2,
    SMILE_3D_PYRAMID = 3,
    SMILE_3D_SPHERE = 4,
    SMILE_3D_CYLINDER = 5,
    SMILE_3D_TORUS = 6
};

long long smile_renderer3d_command(long long command,
    long long a, long long b, long long c, long long d, long long e,
    long long f, long long g, long long h, long long i, long long j);
long long smile_renderer3d_image_command(long long command, void* image,
    long long a, long long b, long long c, long long d,
    long long e, long long f, long long g, long long h);
long long smile_renderer3d_text_command(long long command, void* text,
    long long a, long long b, long long c, long long d,
    long long e, long long f, long long g, long long h);
long long smile_renderer3d_model_text_value(long long command,
    long long model_handle, long long index, char* output, long long capacity);
long long smile_renderer3d_load_model_path(const wchar_t* path);
long long smile_renderer3d_load_model_geometry_path(const wchar_t* path);
long long smile_renderer3d_prepare_model_pbr(long long model_handle,
    long long filter, long long wrap, long long anisotropy);
long long smile_renderer3d_model_text_operation(long long command,
    const char* text, long long length, long long a, long long b, long long c);
void smile_graphics3d_on_device_lost(void);

#ifdef __cplusplus
}
#endif

#endif
